### ISSUE TITLE
Fine-Tuning/Transfer Learning?

### ISSUE THREAD

**Issue by AnujSaharan** [Rongjiehuang/ProDiff#5]
Do you plan to release instructions on how we could use the pre-trained checkpoints to fine-tune on a new dataset formatted like LJSpeech, but for a new single speaker?

**Comment by Rongjiehuang** [comment]
Hi, you can load the pretrained weights and train the model using your custom dataset following [here](https://github.com/Rongjiehuang/ProDiff#train-your-own-model)
