### ISSUE TITLE
Guide Training ProDiff

### ISSUE THREAD

**Issue by tranquangchung** [Rongjiehuang/ProDiff#9]
Thanks for sharing your work.

Can you guide me how to train your framework in more detail, for example, how to train with LJSpeech?

In your guide: Data Preparation and Configuraion
In Preprocess step: $path/to/config
In Align step: $CONFIG_NAME
Binarization step: $path/to/config

I don't know $path/to/config and $CONFIG_NAME that you mention
I use some config in egs, but it doesn't work

Can you support me to use your framework?
Looking forward to hearing from you

**Comment by Rongjiehuang** [comment]
Before training Prodiff, you need a Prodiff teacher using `modules/ProDiff/config/prodiff_teacher.yaml`
After that, train Prodiff with `modules/ProDiff/config/prodiff.yaml`
